---
#- name: List local public keys
#  ansible.builtin.command:
#    cmd: gpg2 --list-keys
#  run_once: true
#  changed_when: false
#  register: _gpg2_list_keys_output

- name: Add keyserver url to gpg.conf.
  ansible.builtin.lineinfile:
    path: "{{ openpgp_config_file_path }}"
    regexp: "^keyserver "
    insertafter: "^#keyserver "
    line: "keyserver {{ public_key.keyserver }}"
    owner: "{{ openpgp_owner }}"
    group: "{{ openpgp_group }}"
    mode: "0400"
  when:
    - public_key.keyserver is defined
    - public_key.id not in _gpg2_list_keys.stdout

- name: Fetch public key from keyserver.
  command:
    cmd: "gpg2 --receive-keys {{ public_key.id }}"
  when: public_key.id not in _gpg2_list_keys.stdout
