---
# tasks files
- name: Include os family variables.
  ansible.builtin.include_vars: "../defaults/{{ ansible_os_family | lower }}.yml"
- name: Include install tasks.
  ansible.builtin.include_tasks: install.yml
- name: Include config tasks.
  ansible.builtin.include_tasks: config.yml
- name: Include service tasks.
  ansible.builtin.include_tasks: service.yml
- debug:
    var: ansible_user
...
