---
- name: Converge
  hosts: all
  tasks:

    - name: "Include variable file"
      ansible.builtin.include_vars: variables.yml

    - name: "Include spreadcat.openpgp"
      ansible.builtin.include_role:
        name: "spreadcat.openpgp"
